### ISSUE TITLE
Day 30: Covid

### ISSUE THREAD

**Issue by mchirico** [mchirico/zDaily#33]
[Video 30](https://vimeo.com/478065938)

# Tasks to Complete
- [x] Accept invite to [zcovid](https://github.com/mchirico/zcovid) and run locally
- [x] Download and run [go-echarts examples](https://github.com/go-echarts/examples)
- [x] Run [CoLab](https://colab.research.google.com/drive/104UOGN6izd358Q_yzUsMjK1bHFRXK2T8?usp=sharing)
- [x] Add comment to Mattermost Covid channel.  

Reference:
[Colab](https://colab.research.google.com/drive/104UOGN6izd358Q_yzUsMjK1bHFRXK2T8?usp=sharing)
[e-charts](https://github.com/go-echarts)
